name: Add issue to projects

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to projects
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/team-tsuruo/projects/1
          github-token: ${{ steps.generate_token.outputs.token }}
